// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NoneventInAppPurchase.proto

package com.lvl6.mobsters.noneventproto;

public final class NoneventInAppPurchaseProto {
  private NoneventInAppPurchaseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum EarnFreeDiamondsType
      implements com.google.protobuf.ProtocolMessageEnum {
    FB_CONNECT(0, 1),
    TAPJOY(1, 2),
    FLURRY_VIDEO(2, 3),
    TWITTER(3, 4),
    ;
    
    public static final int FB_CONNECT_VALUE = 1;
    public static final int TAPJOY_VALUE = 2;
    public static final int FLURRY_VIDEO_VALUE = 3;
    public static final int TWITTER_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static EarnFreeDiamondsType valueOf(int value) {
      switch (value) {
        case 1: return FB_CONNECT;
        case 2: return TAPJOY;
        case 3: return FLURRY_VIDEO;
        case 4: return TWITTER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<EarnFreeDiamondsType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EarnFreeDiamondsType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EarnFreeDiamondsType>() {
            public EarnFreeDiamondsType findValueByNumber(int number) {
              return EarnFreeDiamondsType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final EarnFreeDiamondsType[] VALUES = {
      FB_CONNECT, TAPJOY, FLURRY_VIDEO, TWITTER, 
    };
    
    public static EarnFreeDiamondsType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private EarnFreeDiamondsType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:proto.EarnFreeDiamondsType)
  }
  
  public interface InAppPurchasePackageProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string iapPackageId = 1;
    boolean hasIapPackageId();
    String getIapPackageId();
    
    // optional int32 currencyAmount = 2;
    boolean hasCurrencyAmount();
    int getCurrencyAmount();
    
    // optional string imageName = 3;
    boolean hasImageName();
    String getImageName();
  }
  public static final class InAppPurchasePackageProto extends
      com.google.protobuf.GeneratedMessage
      implements InAppPurchasePackageProtoOrBuilder {
    // Use InAppPurchasePackageProto.newBuilder() to construct.
    private InAppPurchasePackageProto(Builder builder) {
      super(builder);
    }
    private InAppPurchasePackageProto(boolean noInit) {}
    
    private static final InAppPurchasePackageProto defaultInstance;
    public static InAppPurchasePackageProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public InAppPurchasePackageProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.internal_static_proto_InAppPurchasePackageProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.internal_static_proto_InAppPurchasePackageProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string iapPackageId = 1;
    public static final int IAPPACKAGEID_FIELD_NUMBER = 1;
    private java.lang.Object iapPackageId_;
    public boolean hasIapPackageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getIapPackageId() {
      java.lang.Object ref = iapPackageId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          iapPackageId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIapPackageIdBytes() {
      java.lang.Object ref = iapPackageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        iapPackageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 currencyAmount = 2;
    public static final int CURRENCYAMOUNT_FIELD_NUMBER = 2;
    private int currencyAmount_;
    public boolean hasCurrencyAmount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCurrencyAmount() {
      return currencyAmount_;
    }
    
    // optional string imageName = 3;
    public static final int IMAGENAME_FIELD_NUMBER = 3;
    private java.lang.Object imageName_;
    public boolean hasImageName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getImageName() {
      java.lang.Object ref = imageName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imageName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImageNameBytes() {
      java.lang.Object ref = imageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      iapPackageId_ = "";
      currencyAmount_ = 0;
      imageName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIapPackageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, currencyAmount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getImageNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIapPackageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currencyAmount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getImageNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.internal_static_proto_InAppPurchasePackageProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.internal_static_proto_InAppPurchasePackageProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        iapPackageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        currencyAmount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        imageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto build() {
        com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto buildPartial() {
        com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto result = new com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iapPackageId_ = iapPackageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currencyAmount_ = currencyAmount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.imageName_ = imageName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto) {
          return mergeFrom((com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto other) {
        if (other == com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto.getDefaultInstance()) return this;
        if (other.hasIapPackageId()) {
          setIapPackageId(other.getIapPackageId());
        }
        if (other.hasCurrencyAmount()) {
          setCurrencyAmount(other.getCurrencyAmount());
        }
        if (other.hasImageName()) {
          setImageName(other.getImageName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              iapPackageId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currencyAmount_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              imageName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string iapPackageId = 1;
      private java.lang.Object iapPackageId_ = "";
      public boolean hasIapPackageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getIapPackageId() {
        java.lang.Object ref = iapPackageId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          iapPackageId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIapPackageId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        iapPackageId_ = value;
        onChanged();
        return this;
      }
      public Builder clearIapPackageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iapPackageId_ = getDefaultInstance().getIapPackageId();
        onChanged();
        return this;
      }
      void setIapPackageId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        iapPackageId_ = value;
        onChanged();
      }
      
      // optional int32 currencyAmount = 2;
      private int currencyAmount_ ;
      public boolean hasCurrencyAmount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCurrencyAmount() {
        return currencyAmount_;
      }
      public Builder setCurrencyAmount(int value) {
        bitField0_ |= 0x00000002;
        currencyAmount_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrencyAmount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currencyAmount_ = 0;
        onChanged();
        return this;
      }
      
      // optional string imageName = 3;
      private java.lang.Object imageName_ = "";
      public boolean hasImageName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getImageName() {
        java.lang.Object ref = imageName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imageName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImageName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imageName_ = value;
        onChanged();
        return this;
      }
      public Builder clearImageName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        imageName_ = getDefaultInstance().getImageName();
        onChanged();
        return this;
      }
      void setImageName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        imageName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.InAppPurchasePackageProto)
    }
    
    static {
      defaultInstance = new InAppPurchasePackageProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.InAppPurchasePackageProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_InAppPurchasePackageProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_InAppPurchasePackageProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033NoneventInAppPurchase.proto\022\005proto\"\\\n\031" +
      "InAppPurchasePackageProto\022\024\n\014iapPackageI" +
      "d\030\001 \001(\t\022\026\n\016currencyAmount\030\002 \001(\005\022\021\n\timage" +
      "Name\030\003 \001(\t*Q\n\024EarnFreeDiamondsType\022\016\n\nFB" +
      "_CONNECT\020\001\022\n\n\006TAPJOY\020\002\022\020\n\014FLURRY_VIDEO\020\003" +
      "\022\013\n\007TWITTER\020\004B=\n\037com.lvl6.mobsters.nonev" +
      "entprotoB\032NoneventInAppPurchaseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_InAppPurchasePackageProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_InAppPurchasePackageProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_InAppPurchasePackageProto_descriptor,
              new java.lang.String[] { "IapPackageId", "CurrencyAmount", "ImageName", },
              com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto.class,
              com.lvl6.mobsters.noneventproto.NoneventInAppPurchaseProto.InAppPurchasePackageProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
