package com.lvl6.dynamo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="BlacksmithAttemptHistory")
public class BlacksmithAttemptHistory {



	private String id;
	private Long version;

	private BlacksmithAttempt blacksmithAttempt;
	private boolean success;  
	public BlacksmithAttemptHistory(){}
  public BlacksmithAttemptHistory(BlacksmithAttempt blacksmithAttempt,
      boolean success) {
    this.blacksmithAttempt = blacksmithAttempt;
    this.success = success;
  }


	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}


  public BlacksmithAttempt getBlacksmithAttempt() {    return blacksmithAttempt;
  }

  public boolean isSuccess() {
    return success;
  }

  @Override
  public String toString() {
    return "BlacksmithAttemptHistory [blacksmithAttempt=" + blacksmithAttempt
        + ", success=" + success + "]";
  }
  
 	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BlacksmithAttemptHistory other = (BlacksmithAttemptHistory) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}