package com.lvl6.dynamo;
import java.util.Date;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="BlacksmithAttempt")
public class BlacksmithAttempt {



	private String id;
	private Long version;

	
	private int userId;
	private int equipId;
	private int goalLevel;
	private boolean guaranteed;
	private Date startTime;
	private int diamondGuaranteeCost;
	private Date timeOfSpeedup;
	private boolean attemptComplete;
	private int equipOneEnhancementPercent;
	private int equipTwoEnhancementPercent;
	private int forgeSlotNumber;
	public BlacksmithAttempt(){}
  public BlacksmithAttempt(int id, int userId, int equipId, int goalLevel,
      boolean guaranteed, Date startTime, int diamondGuaranteeCost, 
      Date timeOfSpeedup, boolean attemptComplete,
      int equipOneEnhancementPercent, int equipTwoEnhancementPercent,
      int forgeSlotNumber) {
    this.userId = userId;
    this.equipId = equipId;
    this.goalLevel = goalLevel;
    this.guaranteed = guaranteed;
    this.startTime = startTime;
    this.diamondGuaranteeCost = diamondGuaranteeCost;
    this.timeOfSpeedup = timeOfSpeedup;
    this.attemptComplete = attemptComplete;
    this.equipOneEnhancementPercent = equipOneEnhancementPercent;
    this.equipTwoEnhancementPercent = equipTwoEnhancementPercent;
    this.forgeSlotNumber = forgeSlotNumber;
  }



	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}


  public int getUserId() {    return userId;
  }

  public int getEquipId() {
    return equipId;
  }

  public int getGoalLevel() {
    return goalLevel;
  }

  public boolean isGuaranteed() {
    return guaranteed;
  }

  public Date getStartTime() {
    return startTime;
  }

  public int getDiamondGuaranteeCost() {
    return diamondGuaranteeCost;
  }

  public Date getTimeOfSpeedup() {
    return timeOfSpeedup;
  }

  public boolean isAttemptComplete() {
    return attemptComplete;
  }

  public int getEquipOneEnhancementPercent() {
    return equipOneEnhancementPercent;
  }

  public void setEquipOneEnhancementPercent(int equipOneEnhancementPercent) {
    this.equipOneEnhancementPercent = equipOneEnhancementPercent;
  }

  public int getEquipTwoEnhancementPercent() {
    return equipTwoEnhancementPercent;
  }

  public void setEquipTwoEnhancementPercent(int equipTwoEnhancementPercent) {
    this.equipTwoEnhancementPercent = equipTwoEnhancementPercent;
  }

  public int getForgeSlotNumber() {
    return forgeSlotNumber;
  }

  public void setForgeSlotNumber(int forgeSlotNumber) {
    this.forgeSlotNumber = forgeSlotNumber;
  }

  @Override
  public String toString() {
    return "BlacksmithAttempt [id=" + id + ", userId=" + userId + ", equipId="
        + equipId + ", goalLevel=" + goalLevel + ", guaranteed=" + guaranteed
        + ", startTime=" + startTime + ", diamondGuaranteeCost="
        + diamondGuaranteeCost + ", timeOfSpeedup=" + timeOfSpeedup
        + ", attemptComplete=" + attemptComplete
        + ", equipOneEnhancementPercent=" + equipOneEnhancementPercent
        + ", equipTwoEnhancementPercent=" + equipTwoEnhancementPercent
        + ", forgeSlotNumber=" + forgeSlotNumber + "]";
  }

 	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BlacksmithAttempt other = (BlacksmithAttempt) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}