package com.lvl6.dynamo;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="BlacksmithAttemptHistory")
public class BlacksmithAttemptHistory {



	private String id;
	private BlacksmithAttempt blacksmithAttempt;
	private boolean success;  
	public BlacksmithAttemptHistory(){}
  public BlacksmithAttemptHistory(BlacksmithAttempt blacksmithAttempt,
      boolean success) {
    this.blacksmithAttempt = blacksmithAttempt;
    this.success = success;
  }


	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


  public BlacksmithAttempt getBlacksmithAttempt() {    return blacksmithAttempt;
  }

  public boolean isSuccess() {
    return success;
  }

  @Override
  public String toString() {
    return "BlacksmithAttemptHistory [blacksmithAttempt=" + blacksmithAttempt
        + ", success=" + success + "]";
  }
  
}
