package com.lvl6.dynamo;
import java.util.Date;

//user can have multiple of these (different clanIds)

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="CepfuRaidStageHistory")
public class CepfuRaidStageHistory {



	private String id;
	private Long version;

	
	private int userId;
	private Date crsStartTime;
	private int clanId;
	private int clanEventPersistentId;
	private int crId;
	private int crsId;
	private int crsDmgDone;
	private int stageHealth;
	private Date crsEndTime;	
	public CepfuRaidStageHistory(){}
	public CepfuRaidStageHistory(int userId, Date crsStartTime, int clanId,
			int clanEventPersistentId, int crId, int crsId, int crsDmgDone,
			int stageHealth, Date crsEndTime) {
		super();
		this.userId = userId;
		this.crsStartTime = crsStartTime;
		this.clanId = clanId;
		this.clanEventPersistentId = clanEventPersistentId;
		this.crId = crId;
		this.crsId = crsId;
		this.crsDmgDone = crsDmgDone;
		this.stageHealth = stageHealth;
		this.crsEndTime = crsEndTime;
	}


	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}


	public int getUserId() {		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getCrsStartTime() {
		return crsStartTime;
	}

	public void setCrsStartTime(Date crsStartTime) {
		this.crsStartTime = crsStartTime;
	}

	public int getClanId() {
		return clanId;
	}

	public void setClanId(int clanId) {
		this.clanId = clanId;
	}

	public int getClanEventPersistentId() {
		return clanEventPersistentId;
	}

	public void setClanEventPersistentId(int clanEventPersistentId) {
		this.clanEventPersistentId = clanEventPersistentId;
	}

	public int getCrId() {
		return crId;
	}

	public void setCrId(int crId) {
		this.crId = crId;
	}

	public int getCrsId() {
		return crsId;
	}

	public void setCrsId(int crsId) {
		this.crsId = crsId;
	}

	public int getCrsDmgDone() {
		return crsDmgDone;
	}

	public void setCrsDmgDone(int crsDmgDone) {
		this.crsDmgDone = crsDmgDone;
	}

	public int getStageHealth() {
		return stageHealth;
	}

	public void setStageHealth(int stageHealth) {
		this.stageHealth = stageHealth;
	}

	public Date getCrsEndTime() {
		return crsEndTime;
	}

	public void setCrsEndTime(Date crsEndTime) {
		this.crsEndTime = crsEndTime;
	}

	@Override
	public String toString() {
		return "CepfuRaidStageHistory [userId=" + userId + ", crsStartTime="
				+ crsStartTime + ", clanId=" + clanId + ", clanEventPersistentId="
				+ clanEventPersistentId + ", crId=" + crId + ", crsId=" + crsId
				+ ", crsDmgDone=" + crsDmgDone + ", stageHealth=" + stageHealth
				+ ", crsEndTime=" + crsEndTime + "]";
		
	}
 	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CepfuRaidStageHistory other = (CepfuRaidStageHistory) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}