package com.lvl6.dynamo;

import java.util.Date;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="ClanChatPost")
public class ClanChatPost {



	private String id;	
	private int posterId;
	private int clanId;
	private Date timeOfPost;
	private String content;
	public ClanChatPost(){}
  public ClanChatPost(int id, int posterId, int clanId,
      Date timeOfPost, String content) {
    super();
    this.posterId = posterId;
    this.clanId = clanId;
    this.timeOfPost = timeOfPost;
    this.content = content;
  }



	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


  public int getPosterId() {    return posterId;
  }

  public int getClanId() {
    return clanId;
  }

  public Date getTimeOfPost() {
    return timeOfPost;
  }

  public String getContent() {
    return content;
  }

  @Override
  public String toString() {
    return "ClanChatPost [id=" + id + ", posterId=" + posterId
        + ", clanID=" + clanId + ", timeOfPost=" + timeOfPost
        + ", content=" + content + "]";
  }
}
