package com.lvl6.dynamo;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="ClanIcon")
public class ClanIcon {



	private String id;
	

	private String imgName;
	private boolean isAvailable;	
	
	public ClanIcon() {
		super();
	}

	public ClanIcon(int id, String imgName, boolean isAvailable) {
		super();
		this.imgName = imgName;
		this.isAvailable = isAvailable;
	}




	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	public String getImgName() {		return imgName;
	}

	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	public boolean isAvailable() {
		return isAvailable;
	}

	public void setAvailable(boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	@Override
	public String toString() {
		return "ClanIcon [id=" + id + ", imgName=" + imgName + ", isAvailable="
				+ isAvailable + "]";
	}
	
}
