package com.lvl6.dynamo;
//multiple clan raids can be available at the same time

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="ClanRaid")
public class ClanRaid {



	private String id;
	private Long version;

	
	private String clanRaidName;
	private String activeTitleImgName;
	private String activeBackgroundImgName;
	private String activeDescription;
	private String inactiveMonsterImgName;
	private String inactiveDescription;
	private String dialogueText;
	private String spotlightMonsterImgName;	
	public ClanRaid(){}
	public ClanRaid(int id, String clanRaidName, String activeTitleImgName,
			String activeBackgroundImgName, String activeDescription,
			String inactiveMonsterImgName, String inactiveDescription,
			String dialogueText, String spotlightMonsterImgName) {
		super();
		this.clanRaidName = clanRaidName;
		this.activeTitleImgName = activeTitleImgName;
		this.activeBackgroundImgName = activeBackgroundImgName;
		this.activeDescription = activeDescription;
		this.inactiveMonsterImgName = inactiveMonsterImgName;
		this.inactiveDescription = inactiveDescription;
		this.dialogueText = dialogueText;
		this.spotlightMonsterImgName = spotlightMonsterImgName;
	}




	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}


	public String getClanRaidName() {		return clanRaidName;
	}

	public void setClanRaidName(String clanRaidName) {
		this.clanRaidName = clanRaidName;
	}

	public String getActiveTitleImgName() {
		return activeTitleImgName;
	}

	public void setActiveTitleImgName(String activeTitleImgName) {
		this.activeTitleImgName = activeTitleImgName;
	}

	public String getActiveBackgroundImgName() {
		return activeBackgroundImgName;
	}

	public void setActiveBackgroundImgName(String activeBackgroundImgName) {
		this.activeBackgroundImgName = activeBackgroundImgName;
	}

	public String getActiveDescription() {
		return activeDescription;
	}

	public void setActiveDescription(String activeDescription) {
		this.activeDescription = activeDescription;
	}

	public String getInactiveMonsterImgName() {
		return inactiveMonsterImgName;
	}

	public void setInactiveMonsterImgName(String inactiveMonsterImgName) {
		this.inactiveMonsterImgName = inactiveMonsterImgName;
	}

	public String getInactiveDescription() {
		return inactiveDescription;
	}

	public void setInactiveDescription(String inactiveDescription) {
		this.inactiveDescription = inactiveDescription;
	}

	public String getDialogueText() {
		return dialogueText;
	}

	public void setDialogueText(String dialogueText) {
		this.dialogueText = dialogueText;
	}

	public String getSpotlightMonsterImgName() {
		return spotlightMonsterImgName;
	}

	public void setSpotlightMonsterImgName(String spotlightMonsterImgName) {
		this.spotlightMonsterImgName = spotlightMonsterImgName;
	}

	@Override
	public String toString() {
		return "ClanRaid [id=" + id + ", clanRaidName=" + clanRaidName
				+ ", activeTitleImgName=" + activeTitleImgName
				+ ", activeBackgroundImgName=" + activeBackgroundImgName
				+ ", activeDescription=" + activeDescription
				+ ", inactiveMonsterImgName=" + inactiveMonsterImgName
				+ ", inactiveDescription=" + inactiveDescription + ", dialogueText="
				+ dialogueText + ", spotlightMonsterImgName=" + spotlightMonsterImgName
				+ "]";
	}
	
}
