package com.lvl6.dynamo;
import java.util.Set;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="DailyBonusReward")
public class DailyBonusReward {



	private String id;
	private Long version;

	private int minLevel;
	private int maxLevel;
	private int dayOneCoins;
	private int dayTwoCoins;
	private int dayThreeDiamonds;
	private int dayFourCoins;
	
	private Set<Integer> dayFiveBoosterPackIds;  
	public DailyBonusReward(){}
  public DailyBonusReward(int id, int minLevel, int maxLevel, int dayOneCoins,
      int dayTwoCoins, int dayThreeDiamonds, int dayFourCoins,
      Set<Integer> dayFiveBoosterPackIds) {
    super();
    this.minLevel = minLevel;
    this.maxLevel = maxLevel;
    this.dayOneCoins = dayOneCoins;
    this.dayTwoCoins = dayTwoCoins;
    this.dayThreeDiamonds = dayThreeDiamonds;
    this.dayFourCoins = dayFourCoins;
    this.dayFiveBoosterPackIds = dayFiveBoosterPackIds;
  }




	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}


  public int getMinLevel() {    return minLevel;
  }

  public void setMinLevel(int minLevel) {
    this.minLevel = minLevel;
  }

  public int getMaxLevel() {
    return maxLevel;
  }

  public void setMaxLevel(int maxLevel) {
    this.maxLevel = maxLevel;
  }

  public int getDayOneCoins() {
    return dayOneCoins;
  }

  public void setDayOneCoins(int dayOneCoins) {
    this.dayOneCoins = dayOneCoins;
  }

  public int getDayTwoCoins() {
    return dayTwoCoins;
  }

  public void setDayTwoCoins(int dayTwoCoins) {
    this.dayTwoCoins = dayTwoCoins;
  }

  public int getDayThreeDiamonds() {
    return dayThreeDiamonds;
  }

  public void setDayThreeDiamonds(int dayThreeDiamonds) {
    this.dayThreeDiamonds = dayThreeDiamonds;
  }

  public int getDayFourCoins() {
    return dayFourCoins;
  }

  public void setDayFourCoins(int dayFourCoins) {
    this.dayFourCoins = dayFourCoins;
  }

  public Set<Integer> getDayFiveBoosterPackIds() {
    return dayFiveBoosterPackIds;
  }

  public void setDayFiveBoosterPackIds(Set<Integer> dayFiveBoosterPackIds) {
    this.dayFiveBoosterPackIds = dayFiveBoosterPackIds;
  }

  @Override
  public String toString() {
    return "DailyBonusReward [id=" + id + ", minLevel=" + minLevel
        + ", maxLevel=" + maxLevel + ", dayOneCoins=" + dayOneCoins
        + ", dayTwoCoins=" + dayTwoCoins + ", dayThreeDiamonds="
        + dayThreeDiamonds + ", dayFourCoins=" + dayFourCoins
        + ", dayFiveBoosterPackIds=" + dayFiveBoosterPackIds + "]";
  }
  
 	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DailyBonusReward other = (DailyBonusReward) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}