package com.lvl6.dynamo;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="MonsterBattleDialogue")
public class MonsterBattleDialogue {



	private String id;
	
	private int monsterId;
	private String dialogueType;
	private String dialogue;
	private float probabilityUttered;	
	public MonsterBattleDialogue(){}
	public MonsterBattleDialogue(int id, int monsterId, String dialogueType,
			String dialogue, float probabilityUttered) {
		super();
		this.monsterId = monsterId;
		this.dialogueType = dialogueType;
		this.dialogue = dialogue;
		this.probabilityUttered = probabilityUttered;
	}
	

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	public int getMonsterId() {		return monsterId;
	}
	public void setMonsterId(int monsterId) {
		this.monsterId = monsterId;
	}
	public String getDialogueType() {
		return dialogueType;
	}
	public void setDialogueType(String dialogueType) {
		this.dialogueType = dialogueType;
	}
	public String getDialogue() {
		return dialogue;
	}
	public void setDialogue(String dialogue) {
		this.dialogue = dialogue;
	}
	public float getProbabilityUttered() {
		return probabilityUttered;
	}
	public void setProbabilityUttered(float probabilityUttered) {
		this.probabilityUttered = probabilityUttered;
	}

	@Override
	public String toString() {
		return "MonsterBattleDialogue [id=" + id + ", monsterId=" + monsterId
				+ ", dialogueType=" + dialogueType + ", dialogue=" + dialogue
				+ ", probabilityUttered=" + probabilityUttered + "]";
	}
	
}
