package com.lvl6.dynamo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="MonsterReward")
public class MonsterReward {



	private String id;
	private Long version;

	
	private int monsterId;
	private int equipId;
	private float dropRate;	

	public MonsterReward(){}
  public MonsterReward(int id, int monsterId, int equipId, float dropRate) {
    super();
    this.monsterId = monsterId;
    this.equipId = equipId;
    this.dropRate = dropRate;
  }







	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}


  public int getMonsterId() {    return monsterId;
  }


  public void setMonsterId(int monsterId) {
    this.monsterId = monsterId;
  }


  public int getEquipId() {
    return equipId;
  }


  public void setEquipId(int equipId) {
    this.equipId = equipId;
  }


  public float getDropRate() {
    return dropRate;
  }


  public void setDropRate(float dropRate) {
    this.dropRate = dropRate;
  }


  @Override
  public String toString() {
    return "MonsterReward [id=" + id + ", monsterId=" + monsterId
        + ", equipId=" + equipId + ", dropRate=" + dropRate + "]";
  }

 	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MonsterReward other = (MonsterReward) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}