package com.lvl6.dynamo;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="NotificationTitleColor")
public class NotificationTitleColor {



	private String id;	
	private double red;
	private double green;
	private double blue;  
	public NotificationTitleColor(){}
  public NotificationTitleColor(double red, double green, double blue) {
    this.red = red;
    this.green = green;
    this.blue = blue;
  }


	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


  public double getRed() {    return red;
  }

  public double getGreen() {
    return green;
  }

  public double getBlue() {
    return blue;
  }

  @Override
  public String toString() {
    return "UnhandledBlacksmithAttempt [red=" + red + ", green=" + green
        + ", blue=" + blue + "]";
  }
  
}
