package com.lvl6.dynamo;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="PvpLeague")
public class PvpLeague {



	private String id;
	

	private String leagueName;
	private String imgPrefix;
	private int numRanks;
	private String description;
	private int minElo;
	private int maxElo;	
	public PvpLeague(){}
	public PvpLeague(int id, String leagueName, String imgPrefix, int numRanks,
			String description, int minElo, int maxElo) {
		super();
		this.leagueName = leagueName;
		this.imgPrefix = imgPrefix;
		this.numRanks = numRanks;
		this.description = description;
		this.minElo = minElo;
		this.maxElo = maxElo;
	}




	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	public String getLeagueName() {		return leagueName;
	}

	public void setLeagueName(String leagueName) {
		this.leagueName = leagueName;
	}

	public String getImgPrefix() {
		return imgPrefix;
	}

	public void setImgPrefix(String imgPrefix) {
		this.imgPrefix = imgPrefix;
	}

	public int getNumRanks() {
		return numRanks;
	}

	public void setNumRanks(int numRanks) {
		this.numRanks = numRanks;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getMinElo() {
		return minElo;
	}

	public void setMinElo(int minElo) {
		this.minElo = minElo;
	}

	public int getMaxElo() {
		return maxElo;
	}

	public void setMaxElo(int maxElo) {
		this.maxElo = maxElo;
	}

	@Override
	public String toString() {
		return "PvpLeague [id=" + id + ", leagueName=" + leagueName
				+ ", imgPrefix=" + imgPrefix + ", numRanks=" + numRanks
				+ ", description=" + description + ", minElo=" + minElo
				+ ", maxElo=" + maxElo + "]";
	}
	
}
