package com.lvl6.dynamo;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="StaticUserLevelInfo")
public class StaticUserLevelInfo {



	private String id;
	
	private int lvl;
	private int requiredExp;  
	public StaticUserLevelInfo(){}
	public StaticUserLevelInfo(int lvl, int requiredExp) {
		super();
		this.lvl = lvl;
		this.requiredExp = requiredExp;
	}
	

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}


	public int getLvl() {		return lvl;
	}

	public void setLvl(int lvl) {
		this.lvl = lvl;
	}

	public int getRequiredExp() {
		return requiredExp;
	}

	public void setRequiredExp(int requiredExp) {
		this.requiredExp = requiredExp;
	}

	@Override
	public String toString() {
		return "StaticUserLevelInfo [lvl=" + lvl + ", requiredExp=" + requiredExp
				+ "]";
	}
  
}
