package com.lvl6.mobsters.dynamo;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="ClanForUser")
public class ClanForUser {



//	private String id;
	private String userId;
	private String clanId;
	private Long version;

	

	private String status;
	private Date requestTime;
	public ClanForUser(){}
	public ClanForUser(String userId, String clanId, String status, Date requestTime) {
		super();
		this.userId = userId;
		this.clanId = clanId;
		this.status = status;
		this.requestTime = requestTime;
	}
	

//	@DynamoDBAutoGeneratedKey
//	public String getId(){return id;}
//	public void setId(String id){this.id = id;}

	@DynamoDBHashKey(attributeName = "userId")
	public String getUserId() {		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBRangeKey(attributeName = "clanId")
	public String getClanId() {
		return clanId;
	}
	public void setClanId(String clanId) {
		this.clanId = clanId;
	}

	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}


	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public Date getRequestTime() {
		return requestTime;
	}
	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}
	
	@Override
	public String toString() {
		return "UserClan [userId=" + userId + ", clanId=" + clanId
				+ ", status=" + status + ", requestTime=" + requestTime + "]";
	}
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime
			* result
			+ ((clanId == null) ? 0 : clanId.hashCode());
		result = prime
			* result
			+ ((userId == null) ? 0 : userId.hashCode());
		return result;
	}
	@Override
	public boolean equals( Object obj )
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClanForUser other = (ClanForUser) obj;
		if (clanId == null) {
			if (other.clanId != null)
				return false;
		} else if (!clanId.equals(other.clanId))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		return true;
	}

}
