package com.lvl6.mobsters.dynamo;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="MonsterHealingForUser")
public class MonsterHealingForUser {



//	private String id;
	private String userId;
	private String monsterForUserId;
	private Long version;

	
	private Date queuedTime;
//	private int userStructHospitalId;
	private float healthProgress;
	private int priority;  
	public MonsterHealingForUser(){}
	public MonsterHealingForUser(String userId, String monsterForUserId,
			Date queuedTime, float healthProgress, int priority) {
		super();
		this.userId = userId;
		this.monsterForUserId = monsterForUserId;
		this.queuedTime = queuedTime;
		this.healthProgress = healthProgress;
		this.priority = priority;
	}


	/*@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}*/

	@DynamoDBHashKey(attributeName = "userId")
	public String getUserId() {		return userId;
	}
	
	public void setUserId(String userId) {
		this.userId = userId;
	}

	@DynamoDBRangeKey(attributeName = "monsterForUserId")
	public String getMonsterForUserId() {
		return monsterForUserId;
	}
	
	public void setMonsterForUserId(String monsterForUserId) {
		this.monsterForUserId = monsterForUserId;
	}

	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}


	public Date getQueuedTime() {
		return queuedTime;
	}

	public void setQueuedTime(Date queuedTime) {
		this.queuedTime = queuedTime;
	}

	public float getHealthProgress() {
		return healthProgress;
	}

	public void setHealthProgress(float healthProgress) {
		this.healthProgress = healthProgress;
	}

	public int getPriority() {
		return priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Override
	public String toString() {
		return "MonsterHealingForUser [userId=" + userId + ", monsterForUserId="
				+ monsterForUserId + ", queuedTime=" + queuedTime + ", healthProgress="
				+ healthProgress + ", priority=" + priority + "]";
	}
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime
			* result
			+ ((monsterForUserId == null) ? 0 : monsterForUserId.hashCode());
		result = prime
			* result
			+ ((userId == null) ? 0 : userId.hashCode());
		return result;
	}
	@Override
	public boolean equals( Object obj )
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MonsterHealingForUser other = (MonsterHealingForUser) obj;
		if (monsterForUserId == null) {
			if (other.monsterForUserId != null)
				return false;
		} else if (!monsterForUserId.equals(other.monsterForUserId))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		return true;
	}
  
}
