package com.lvl6.mobsters.dynamo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="TaskStageForUser")
public class TaskStageForUser {



//	private String id;
	private String taskForUserId;
	private String taskStageForUserId;
	private Long version;

	
	private int stageNum;
	private int taskStageMonsterId; //not task stage monster monster id
	private String monsterType;
	private int expGained;
	private int cashGained;
	private int oilGained;
	private boolean monsterPieceDropped;
	private int itemIdDropped;	//maybe should specify the (enhancement) level of monster dropped
	
	public TaskStageForUser(){}
	public TaskStageForUser(String taskForUserId, int stageNum,
			int taskStageMonsterId, String monsterType, int expGained,
			int cashGained, int oilGained, boolean monsterPieceDropped,
			int itemIdDropped) {
		super();
		this.taskForUserId = taskForUserId;
		this.stageNum = stageNum;
		this.taskStageMonsterId = taskStageMonsterId;
		this.monsterType = monsterType;
		this.expGained = expGained;
		this.cashGained = cashGained;
		this.oilGained = oilGained;
		this.monsterPieceDropped = monsterPieceDropped;
		this.itemIdDropped = itemIdDropped;
	}

/*
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId(){return id;}
	public void setId(String id){this.id = id;}
*/
	
	
	@DynamoDBHashKey(attributeName = "taskForUserId")
	public String getTaskForUserId() {		return taskForUserId;
	}
	
	public void setTaskForUserId(String taskForUserId) {
		this.taskForUserId = taskForUserId;
	}
	
	@DynamoDBRangeKey(attributeName = "taskStageForUserId")
	@DynamoDBAutoGeneratedKey
	public String getTaskStageForUserId()
	{
		return taskStageForUserId;
	}
	public void setTaskStageForUserId( String taskStageForUserId )
	{
		this.taskStageForUserId = taskStageForUserId;
	}

	@DynamoDBVersionAttribute
	public Long getVersion(){return version;}
	public void setVersion(Long version){this.version = version;}
	public int getStageNum() {
		return stageNum;
	}
	
	public void setStageNum(int stageNum) {
		this.stageNum = stageNum;
	}

	public int getTaskStageMonsterId() {
		return taskStageMonsterId;
	}

	public void setTaskStageMonsterId(int taskStageMonsterId) {
		this.taskStageMonsterId = taskStageMonsterId;
	}

	public String getMonsterType() {
		return monsterType;
	}

	public void setMonsterType(String monsterType) {
		this.monsterType = monsterType;
	}

	public int getExpGained() {
		return expGained;
	}

	public void setExpGained(int expGained) {
		this.expGained = expGained;
	}

	public int getCashGained() {
		return cashGained;
	}

	public void setCashGained(int cashGained) {
		this.cashGained = cashGained;
	}

	public int getOilGained() {
		return oilGained;
	}

	public void setOilGained(int oilGained) {
		this.oilGained = oilGained;
	}

	public boolean isMonsterPieceDropped() {
		return monsterPieceDropped;
	}

	public void setMonsterPieceDropped(boolean monsterPieceDropped) {
		this.monsterPieceDropped = monsterPieceDropped;
	}

	public int getItemIdDropped() {
		return itemIdDropped;
	}

	public void setItemIdDropped(int itemIdDropped) {
		this.itemIdDropped = itemIdDropped;
	}

}
