<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metadata" nsURI="com.lvl6.mobsters.domainmodel.metadata" nsPrefix="metadata">
  <eClassifiers xsi:type="ecore:EDataType" name="IMonster" instanceClassName="com.lvl6.mobsters.info.IMonster"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IItem" instanceClassName="com.lvl6.mobsters.info.IItem"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ITask" instanceClassName="com.lvl6.mobsters.info.ITask"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ITaskStage" instanceClassName="com.lvl6.mobsters.info.ITaskStage"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ITaskStageMonster" instanceClassName="com.lvl6.mobsters.info.ITaskStageMonster"/>
  <eClassifiers xsi:type="ecore:EDataType" name="QuestMeta" instanceClassName="int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="QuestJobMeta" instanceClassName="int"/>
</ecore:EPackage>
