// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AchievementStuff.proto

package com.lvl6.proto;

public final class AchievementStuffProto {
  private AchievementStuffProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AchievementProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 achievementId = 1;
    boolean hasAchievementId();
    int getAchievementId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // optional int32 gemReward = 4;
    boolean hasGemReward();
    int getGemReward();
    
    // optional int32 lvl = 5;
    boolean hasLvl();
    int getLvl();
    
    // optional .com.lvl6.proto.AchievementProto.AchievementType achievementType = 6;
    boolean hasAchievementType();
    com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType getAchievementType();
    
    // optional .com.lvl6.proto.ResourceType resourceType = 7 [default = NO_RESOURCE];
    boolean hasResourceType();
    com.lvl6.proto.StructureProto.ResourceType getResourceType();
    
    // optional .com.lvl6.proto.Element element = 8 [default = NO_ELEMENT];
    boolean hasElement();
    com.lvl6.proto.SharedEnumConfigProto.Element getElement();
    
    // optional .com.lvl6.proto.Quality quality = 9 [default = NO_QUALITY];
    boolean hasQuality();
    com.lvl6.proto.SharedEnumConfigProto.Quality getQuality();
    
    // optional int32 staticDataId = 10;
    boolean hasStaticDataId();
    int getStaticDataId();
    
    // optional int32 quantity = 11;
    boolean hasQuantity();
    int getQuantity();
    
    // optional int32 priority = 12;
    boolean hasPriority();
    int getPriority();
    
    // optional int32 prerequisiteId = 13;
    boolean hasPrerequisiteId();
    int getPrerequisiteId();
    
    // optional int32 successorId = 14;
    boolean hasSuccessorId();
    int getSuccessorId();
  }
  public static final class AchievementProto extends
      com.google.protobuf.GeneratedMessage
      implements AchievementProtoOrBuilder {
    // Use AchievementProto.newBuilder() to construct.
    private AchievementProto(Builder builder) {
      super(builder);
    }
    private AchievementProto(boolean noInit) {}
    
    private static final AchievementProto defaultInstance;
    public static AchievementProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public AchievementProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.AchievementStuffProto.internal_static_com_lvl6_proto_AchievementProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.AchievementStuffProto.internal_static_com_lvl6_proto_AchievementProto_fieldAccessorTable;
    }
    
    public enum AchievementType
        implements com.google.protobuf.ProtocolMessageEnum {
      NO_ACHIEVEMENT(0, 17),
      COLLECT_RESOURCE(1, 1),
      CREATE_GRENADE(2, 2),
      CREATE_RAINBOW(3, 3),
      CREATE_ROCKET(4, 4),
      DEFEAT_MONSTERS(5, 5),
      DESTROY_ORBS(6, 6),
      ENHANCE_POINTS(7, 7),
      HEAL_MONSTERS(8, 8),
      JOIN_LEAGUE(9, 9),
      MAKE_COMBO(10, 10),
      REMOVE_OBSTACLE(11, 11),
      SELL_MONSTER(12, 12),
      STEAL_RESOURCE(13, 13),
      TAKE_DAMAGE(14, 14),
      UPGRADE_BUILDING(15, 15),
      WIN_PVP_BATTLE(16, 16),
      ;
      
      public static final int NO_ACHIEVEMENT_VALUE = 17;
      public static final int COLLECT_RESOURCE_VALUE = 1;
      public static final int CREATE_GRENADE_VALUE = 2;
      public static final int CREATE_RAINBOW_VALUE = 3;
      public static final int CREATE_ROCKET_VALUE = 4;
      public static final int DEFEAT_MONSTERS_VALUE = 5;
      public static final int DESTROY_ORBS_VALUE = 6;
      public static final int ENHANCE_POINTS_VALUE = 7;
      public static final int HEAL_MONSTERS_VALUE = 8;
      public static final int JOIN_LEAGUE_VALUE = 9;
      public static final int MAKE_COMBO_VALUE = 10;
      public static final int REMOVE_OBSTACLE_VALUE = 11;
      public static final int SELL_MONSTER_VALUE = 12;
      public static final int STEAL_RESOURCE_VALUE = 13;
      public static final int TAKE_DAMAGE_VALUE = 14;
      public static final int UPGRADE_BUILDING_VALUE = 15;
      public static final int WIN_PVP_BATTLE_VALUE = 16;
      
      
      public final int getNumber() { return value; }
      
      public static AchievementType valueOf(int value) {
        switch (value) {
          case 17: return NO_ACHIEVEMENT;
          case 1: return COLLECT_RESOURCE;
          case 2: return CREATE_GRENADE;
          case 3: return CREATE_RAINBOW;
          case 4: return CREATE_ROCKET;
          case 5: return DEFEAT_MONSTERS;
          case 6: return DESTROY_ORBS;
          case 7: return ENHANCE_POINTS;
          case 8: return HEAL_MONSTERS;
          case 9: return JOIN_LEAGUE;
          case 10: return MAKE_COMBO;
          case 11: return REMOVE_OBSTACLE;
          case 12: return SELL_MONSTER;
          case 13: return STEAL_RESOURCE;
          case 14: return TAKE_DAMAGE;
          case 15: return UPGRADE_BUILDING;
          case 16: return WIN_PVP_BATTLE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<AchievementType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<AchievementType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AchievementType>() {
              public AchievementType findValueByNumber(int number) {
                return AchievementType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.proto.AchievementStuffProto.AchievementProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final AchievementType[] VALUES = {
        NO_ACHIEVEMENT, COLLECT_RESOURCE, CREATE_GRENADE, CREATE_RAINBOW, CREATE_ROCKET, DEFEAT_MONSTERS, DESTROY_ORBS, ENHANCE_POINTS, HEAL_MONSTERS, JOIN_LEAGUE, MAKE_COMBO, REMOVE_OBSTACLE, SELL_MONSTER, STEAL_RESOURCE, TAKE_DAMAGE, UPGRADE_BUILDING, WIN_PVP_BATTLE, 
      };
      
      public static AchievementType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private AchievementType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.lvl6.proto.AchievementProto.AchievementType)
    }
    
    private int bitField0_;
    // optional int32 achievementId = 1;
    public static final int ACHIEVEMENTID_FIELD_NUMBER = 1;
    private int achievementId_;
    public boolean hasAchievementId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAchievementId() {
      return achievementId_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 gemReward = 4;
    public static final int GEMREWARD_FIELD_NUMBER = 4;
    private int gemReward_;
    public boolean hasGemReward() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getGemReward() {
      return gemReward_;
    }
    
    // optional int32 lvl = 5;
    public static final int LVL_FIELD_NUMBER = 5;
    private int lvl_;
    public boolean hasLvl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getLvl() {
      return lvl_;
    }
    
    // optional .com.lvl6.proto.AchievementProto.AchievementType achievementType = 6;
    public static final int ACHIEVEMENTTYPE_FIELD_NUMBER = 6;
    private com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType achievementType_;
    public boolean hasAchievementType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType getAchievementType() {
      return achievementType_;
    }
    
    // optional .com.lvl6.proto.ResourceType resourceType = 7 [default = NO_RESOURCE];
    public static final int RESOURCETYPE_FIELD_NUMBER = 7;
    private com.lvl6.proto.StructureProto.ResourceType resourceType_;
    public boolean hasResourceType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.lvl6.proto.StructureProto.ResourceType getResourceType() {
      return resourceType_;
    }
    
    // optional .com.lvl6.proto.Element element = 8 [default = NO_ELEMENT];
    public static final int ELEMENT_FIELD_NUMBER = 8;
    private com.lvl6.proto.SharedEnumConfigProto.Element element_;
    public boolean hasElement() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.lvl6.proto.SharedEnumConfigProto.Element getElement() {
      return element_;
    }
    
    // optional .com.lvl6.proto.Quality quality = 9 [default = NO_QUALITY];
    public static final int QUALITY_FIELD_NUMBER = 9;
    private com.lvl6.proto.SharedEnumConfigProto.Quality quality_;
    public boolean hasQuality() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public com.lvl6.proto.SharedEnumConfigProto.Quality getQuality() {
      return quality_;
    }
    
    // optional int32 staticDataId = 10;
    public static final int STATICDATAID_FIELD_NUMBER = 10;
    private int staticDataId_;
    public boolean hasStaticDataId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getStaticDataId() {
      return staticDataId_;
    }
    
    // optional int32 quantity = 11;
    public static final int QUANTITY_FIELD_NUMBER = 11;
    private int quantity_;
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getQuantity() {
      return quantity_;
    }
    
    // optional int32 priority = 12;
    public static final int PRIORITY_FIELD_NUMBER = 12;
    private int priority_;
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getPriority() {
      return priority_;
    }
    
    // optional int32 prerequisiteId = 13;
    public static final int PREREQUISITEID_FIELD_NUMBER = 13;
    private int prerequisiteId_;
    public boolean hasPrerequisiteId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getPrerequisiteId() {
      return prerequisiteId_;
    }
    
    // optional int32 successorId = 14;
    public static final int SUCCESSORID_FIELD_NUMBER = 14;
    private int successorId_;
    public boolean hasSuccessorId() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getSuccessorId() {
      return successorId_;
    }
    
    private void initFields() {
      achievementId_ = 0;
      name_ = "";
      description_ = "";
      gemReward_ = 0;
      lvl_ = 0;
      achievementType_ = com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType.NO_ACHIEVEMENT;
      resourceType_ = com.lvl6.proto.StructureProto.ResourceType.NO_RESOURCE;
      element_ = com.lvl6.proto.SharedEnumConfigProto.Element.NO_ELEMENT;
      quality_ = com.lvl6.proto.SharedEnumConfigProto.Quality.NO_QUALITY;
      staticDataId_ = 0;
      quantity_ = 0;
      priority_ = 0;
      prerequisiteId_ = 0;
      successorId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, achievementId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, gemReward_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, lvl_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, achievementType_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, resourceType_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, element_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeEnum(9, quality_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, staticDataId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, quantity_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, priority_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, prerequisiteId_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, successorId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, achievementId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gemReward_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, lvl_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, achievementType_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, resourceType_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, element_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, quality_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, staticDataId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, quantity_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, priority_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, prerequisiteId_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, successorId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.AchievementProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.AchievementStuffProto.AchievementProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.AchievementStuffProto.AchievementProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.AchievementStuffProto.internal_static_com_lvl6_proto_AchievementProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.AchievementStuffProto.internal_static_com_lvl6_proto_AchievementProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.AchievementStuffProto.AchievementProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        achievementId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        gemReward_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        lvl_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        achievementType_ = com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType.NO_ACHIEVEMENT;
        bitField0_ = (bitField0_ & ~0x00000020);
        resourceType_ = com.lvl6.proto.StructureProto.ResourceType.NO_RESOURCE;
        bitField0_ = (bitField0_ & ~0x00000040);
        element_ = com.lvl6.proto.SharedEnumConfigProto.Element.NO_ELEMENT;
        bitField0_ = (bitField0_ & ~0x00000080);
        quality_ = com.lvl6.proto.SharedEnumConfigProto.Quality.NO_QUALITY;
        bitField0_ = (bitField0_ & ~0x00000100);
        staticDataId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        priority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        prerequisiteId_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        successorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.AchievementStuffProto.AchievementProto.getDescriptor();
      }
      
      public com.lvl6.proto.AchievementStuffProto.AchievementProto getDefaultInstanceForType() {
        return com.lvl6.proto.AchievementStuffProto.AchievementProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.AchievementStuffProto.AchievementProto build() {
        com.lvl6.proto.AchievementStuffProto.AchievementProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.AchievementStuffProto.AchievementProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.AchievementStuffProto.AchievementProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.AchievementStuffProto.AchievementProto buildPartial() {
        com.lvl6.proto.AchievementStuffProto.AchievementProto result = new com.lvl6.proto.AchievementStuffProto.AchievementProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.achievementId_ = achievementId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gemReward_ = gemReward_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lvl_ = lvl_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.achievementType_ = achievementType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.resourceType_ = resourceType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.element_ = element_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.quality_ = quality_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.staticDataId_ = staticDataId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.prerequisiteId_ = prerequisiteId_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.successorId_ = successorId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.AchievementStuffProto.AchievementProto) {
          return mergeFrom((com.lvl6.proto.AchievementStuffProto.AchievementProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.AchievementStuffProto.AchievementProto other) {
        if (other == com.lvl6.proto.AchievementStuffProto.AchievementProto.getDefaultInstance()) return this;
        if (other.hasAchievementId()) {
          setAchievementId(other.getAchievementId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasGemReward()) {
          setGemReward(other.getGemReward());
        }
        if (other.hasLvl()) {
          setLvl(other.getLvl());
        }
        if (other.hasAchievementType()) {
          setAchievementType(other.getAchievementType());
        }
        if (other.hasResourceType()) {
          setResourceType(other.getResourceType());
        }
        if (other.hasElement()) {
          setElement(other.getElement());
        }
        if (other.hasQuality()) {
          setQuality(other.getQuality());
        }
        if (other.hasStaticDataId()) {
          setStaticDataId(other.getStaticDataId());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasPrerequisiteId()) {
          setPrerequisiteId(other.getPrerequisiteId());
        }
        if (other.hasSuccessorId()) {
          setSuccessorId(other.getSuccessorId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              achievementId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gemReward_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              lvl_ = input.readInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType value = com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                achievementType_ = value;
              }
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.lvl6.proto.StructureProto.ResourceType value = com.lvl6.proto.StructureProto.ResourceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                resourceType_ = value;
              }
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              com.lvl6.proto.SharedEnumConfigProto.Element value = com.lvl6.proto.SharedEnumConfigProto.Element.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                element_ = value;
              }
              break;
            }
            case 72: {
              int rawValue = input.readEnum();
              com.lvl6.proto.SharedEnumConfigProto.Quality value = com.lvl6.proto.SharedEnumConfigProto.Quality.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(9, rawValue);
              } else {
                bitField0_ |= 0x00000100;
                quality_ = value;
              }
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              staticDataId_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              quantity_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              priority_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              prerequisiteId_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              successorId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 achievementId = 1;
      private int achievementId_ ;
      public boolean hasAchievementId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAchievementId() {
        return achievementId_;
      }
      public Builder setAchievementId(int value) {
        bitField0_ |= 0x00000001;
        achievementId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAchievementId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        achievementId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // optional int32 gemReward = 4;
      private int gemReward_ ;
      public boolean hasGemReward() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getGemReward() {
        return gemReward_;
      }
      public Builder setGemReward(int value) {
        bitField0_ |= 0x00000008;
        gemReward_ = value;
        onChanged();
        return this;
      }
      public Builder clearGemReward() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gemReward_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 lvl = 5;
      private int lvl_ ;
      public boolean hasLvl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getLvl() {
        return lvl_;
      }
      public Builder setLvl(int value) {
        bitField0_ |= 0x00000010;
        lvl_ = value;
        onChanged();
        return this;
      }
      public Builder clearLvl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lvl_ = 0;
        onChanged();
        return this;
      }
      
      // optional .com.lvl6.proto.AchievementProto.AchievementType achievementType = 6;
      private com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType achievementType_ = com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType.NO_ACHIEVEMENT;
      public boolean hasAchievementType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType getAchievementType() {
        return achievementType_;
      }
      public Builder setAchievementType(com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        achievementType_ = value;
        onChanged();
        return this;
      }
      public Builder clearAchievementType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        achievementType_ = com.lvl6.proto.AchievementStuffProto.AchievementProto.AchievementType.NO_ACHIEVEMENT;
        onChanged();
        return this;
      }
      
      // optional .com.lvl6.proto.ResourceType resourceType = 7 [default = NO_RESOURCE];
      private com.lvl6.proto.StructureProto.ResourceType resourceType_ = com.lvl6.proto.StructureProto.ResourceType.NO_RESOURCE;
      public boolean hasResourceType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public com.lvl6.proto.StructureProto.ResourceType getResourceType() {
        return resourceType_;
      }
      public Builder setResourceType(com.lvl6.proto.StructureProto.ResourceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        resourceType_ = value;
        onChanged();
        return this;
      }
      public Builder clearResourceType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        resourceType_ = com.lvl6.proto.StructureProto.ResourceType.NO_RESOURCE;
        onChanged();
        return this;
      }
      
      // optional .com.lvl6.proto.Element element = 8 [default = NO_ELEMENT];
      private com.lvl6.proto.SharedEnumConfigProto.Element element_ = com.lvl6.proto.SharedEnumConfigProto.Element.NO_ELEMENT;
      public boolean hasElement() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.lvl6.proto.SharedEnumConfigProto.Element getElement() {
        return element_;
      }
      public Builder setElement(com.lvl6.proto.SharedEnumConfigProto.Element value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        element_ = value;
        onChanged();
        return this;
      }
      public Builder clearElement() {
        bitField0_ = (bitField0_ & ~0x00000080);
        element_ = com.lvl6.proto.SharedEnumConfigProto.Element.NO_ELEMENT;
        onChanged();
        return this;
      }
      
      // optional .com.lvl6.proto.Quality quality = 9 [default = NO_QUALITY];
      private com.lvl6.proto.SharedEnumConfigProto.Quality quality_ = com.lvl6.proto.SharedEnumConfigProto.Quality.NO_QUALITY;
      public boolean hasQuality() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public com.lvl6.proto.SharedEnumConfigProto.Quality getQuality() {
        return quality_;
      }
      public Builder setQuality(com.lvl6.proto.SharedEnumConfigProto.Quality value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        quality_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuality() {
        bitField0_ = (bitField0_ & ~0x00000100);
        quality_ = com.lvl6.proto.SharedEnumConfigProto.Quality.NO_QUALITY;
        onChanged();
        return this;
      }
      
      // optional int32 staticDataId = 10;
      private int staticDataId_ ;
      public boolean hasStaticDataId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getStaticDataId() {
        return staticDataId_;
      }
      public Builder setStaticDataId(int value) {
        bitField0_ |= 0x00000200;
        staticDataId_ = value;
        onChanged();
        return this;
      }
      public Builder clearStaticDataId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        staticDataId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 quantity = 11;
      private int quantity_ ;
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getQuantity() {
        return quantity_;
      }
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000400;
        quantity_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000400);
        quantity_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 priority = 12;
      private int priority_ ;
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getPriority() {
        return priority_;
      }
      public Builder setPriority(int value) {
        bitField0_ |= 0x00000800;
        priority_ = value;
        onChanged();
        return this;
      }
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000800);
        priority_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 prerequisiteId = 13;
      private int prerequisiteId_ ;
      public boolean hasPrerequisiteId() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getPrerequisiteId() {
        return prerequisiteId_;
      }
      public Builder setPrerequisiteId(int value) {
        bitField0_ |= 0x00001000;
        prerequisiteId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrerequisiteId() {
        bitField0_ = (bitField0_ & ~0x00001000);
        prerequisiteId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 successorId = 14;
      private int successorId_ ;
      public boolean hasSuccessorId() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getSuccessorId() {
        return successorId_;
      }
      public Builder setSuccessorId(int value) {
        bitField0_ |= 0x00002000;
        successorId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSuccessorId() {
        bitField0_ = (bitField0_ & ~0x00002000);
        successorId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.AchievementProto)
    }
    
    static {
      defaultInstance = new AchievementProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.AchievementProto)
  }
  
  public interface UserAchievementProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 achievementId = 1;
    boolean hasAchievementId();
    int getAchievementId();
    
    // optional int32 progress = 2;
    boolean hasProgress();
    int getProgress();
    
    // optional bool isComplete = 3;
    boolean hasIsComplete();
    boolean getIsComplete();
    
    // optional bool isRedeemed = 4;
    boolean hasIsRedeemed();
    boolean getIsRedeemed();
  }
  public static final class UserAchievementProto extends
      com.google.protobuf.GeneratedMessage
      implements UserAchievementProtoOrBuilder {
    // Use UserAchievementProto.newBuilder() to construct.
    private UserAchievementProto(Builder builder) {
      super(builder);
    }
    private UserAchievementProto(boolean noInit) {}
    
    private static final UserAchievementProto defaultInstance;
    public static UserAchievementProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserAchievementProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.AchievementStuffProto.internal_static_com_lvl6_proto_UserAchievementProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.AchievementStuffProto.internal_static_com_lvl6_proto_UserAchievementProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 achievementId = 1;
    public static final int ACHIEVEMENTID_FIELD_NUMBER = 1;
    private int achievementId_;
    public boolean hasAchievementId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAchievementId() {
      return achievementId_;
    }
    
    // optional int32 progress = 2;
    public static final int PROGRESS_FIELD_NUMBER = 2;
    private int progress_;
    public boolean hasProgress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getProgress() {
      return progress_;
    }
    
    // optional bool isComplete = 3;
    public static final int ISCOMPLETE_FIELD_NUMBER = 3;
    private boolean isComplete_;
    public boolean hasIsComplete() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getIsComplete() {
      return isComplete_;
    }
    
    // optional bool isRedeemed = 4;
    public static final int ISREDEEMED_FIELD_NUMBER = 4;
    private boolean isRedeemed_;
    public boolean hasIsRedeemed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getIsRedeemed() {
      return isRedeemed_;
    }
    
    private void initFields() {
      achievementId_ = 0;
      progress_ = 0;
      isComplete_ = false;
      isRedeemed_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, achievementId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, progress_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isComplete_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isRedeemed_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, achievementId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, progress_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isComplete_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isRedeemed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.AchievementStuffProto.UserAchievementProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.AchievementStuffProto.UserAchievementProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.AchievementStuffProto.UserAchievementProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.AchievementStuffProto.internal_static_com_lvl6_proto_UserAchievementProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.AchievementStuffProto.internal_static_com_lvl6_proto_UserAchievementProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.AchievementStuffProto.UserAchievementProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        achievementId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        progress_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isComplete_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        isRedeemed_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.AchievementStuffProto.UserAchievementProto.getDescriptor();
      }
      
      public com.lvl6.proto.AchievementStuffProto.UserAchievementProto getDefaultInstanceForType() {
        return com.lvl6.proto.AchievementStuffProto.UserAchievementProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.AchievementStuffProto.UserAchievementProto build() {
        com.lvl6.proto.AchievementStuffProto.UserAchievementProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.AchievementStuffProto.UserAchievementProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.AchievementStuffProto.UserAchievementProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.AchievementStuffProto.UserAchievementProto buildPartial() {
        com.lvl6.proto.AchievementStuffProto.UserAchievementProto result = new com.lvl6.proto.AchievementStuffProto.UserAchievementProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.achievementId_ = achievementId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.progress_ = progress_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isComplete_ = isComplete_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isRedeemed_ = isRedeemed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.AchievementStuffProto.UserAchievementProto) {
          return mergeFrom((com.lvl6.proto.AchievementStuffProto.UserAchievementProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.AchievementStuffProto.UserAchievementProto other) {
        if (other == com.lvl6.proto.AchievementStuffProto.UserAchievementProto.getDefaultInstance()) return this;
        if (other.hasAchievementId()) {
          setAchievementId(other.getAchievementId());
        }
        if (other.hasProgress()) {
          setProgress(other.getProgress());
        }
        if (other.hasIsComplete()) {
          setIsComplete(other.getIsComplete());
        }
        if (other.hasIsRedeemed()) {
          setIsRedeemed(other.getIsRedeemed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              achievementId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              progress_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isComplete_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isRedeemed_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 achievementId = 1;
      private int achievementId_ ;
      public boolean hasAchievementId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAchievementId() {
        return achievementId_;
      }
      public Builder setAchievementId(int value) {
        bitField0_ |= 0x00000001;
        achievementId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAchievementId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        achievementId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 progress = 2;
      private int progress_ ;
      public boolean hasProgress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getProgress() {
        return progress_;
      }
      public Builder setProgress(int value) {
        bitField0_ |= 0x00000002;
        progress_ = value;
        onChanged();
        return this;
      }
      public Builder clearProgress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        progress_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool isComplete = 3;
      private boolean isComplete_ ;
      public boolean hasIsComplete() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getIsComplete() {
        return isComplete_;
      }
      public Builder setIsComplete(boolean value) {
        bitField0_ |= 0x00000004;
        isComplete_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsComplete() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isComplete_ = false;
        onChanged();
        return this;
      }
      
      // optional bool isRedeemed = 4;
      private boolean isRedeemed_ ;
      public boolean hasIsRedeemed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getIsRedeemed() {
        return isRedeemed_;
      }
      public Builder setIsRedeemed(boolean value) {
        bitField0_ |= 0x00000008;
        isRedeemed_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsRedeemed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isRedeemed_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.UserAchievementProto)
    }
    
    static {
      defaultInstance = new UserAchievementProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.UserAchievementProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_AchievementProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_AchievementProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_UserAchievementProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_UserAchievementProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026AchievementStuff.proto\022\016com.lvl6.proto" +
      "\032\022MonsterStuff.proto\032\026SharedEnumConfig.p" +
      "roto\032\017Structure.proto\"\251\006\n\020AchievementPro" +
      "to\022\025\n\rachievementId\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022" +
      "\023\n\013description\030\003 \001(\t\022\021\n\tgemReward\030\004 \001(\005\022" +
      "\013\n\003lvl\030\005 \001(\005\022I\n\017achievementType\030\006 \001(\01620." +
      "com.lvl6.proto.AchievementProto.Achievem" +
      "entType\022?\n\014resourceType\030\007 \001(\0162\034.com.lvl6" +
      ".proto.ResourceType:\013NO_RESOURCE\0224\n\007elem" +
      "ent\030\010 \001(\0162\027.com.lvl6.proto.Element:\nNO_E",
      "LEMENT\0224\n\007quality\030\t \001(\0162\027.com.lvl6.proto" +
      ".Quality:\nNO_QUALITY\022\024\n\014staticDataId\030\n \001" +
      "(\005\022\020\n\010quantity\030\013 \001(\005\022\020\n\010priority\030\014 \001(\005\022\026" +
      "\n\016prerequisiteId\030\r \001(\005\022\023\n\013successorId\030\016 " +
      "\001(\005\"\333\002\n\017AchievementType\022\022\n\016NO_ACHIEVEMEN" +
      "T\020\021\022\024\n\020COLLECT_RESOURCE\020\001\022\022\n\016CREATE_GREN" +
      "ADE\020\002\022\022\n\016CREATE_RAINBOW\020\003\022\021\n\rCREATE_ROCK" +
      "ET\020\004\022\023\n\017DEFEAT_MONSTERS\020\005\022\020\n\014DESTROY_ORB" +
      "S\020\006\022\022\n\016ENHANCE_POINTS\020\007\022\021\n\rHEAL_MONSTERS" +
      "\020\010\022\017\n\013JOIN_LEAGUE\020\t\022\016\n\nMAKE_COMBO\020\n\022\023\n\017R",
      "EMOVE_OBSTACLE\020\013\022\020\n\014SELL_MONSTER\020\014\022\022\n\016ST" +
      "EAL_RESOURCE\020\r\022\017\n\013TAKE_DAMAGE\020\016\022\024\n\020UPGRA" +
      "DE_BUILDING\020\017\022\022\n\016WIN_PVP_BATTLE\020\020\"g\n\024Use" +
      "rAchievementProto\022\025\n\rachievementId\030\001 \001(\005" +
      "\022\020\n\010progress\030\002 \001(\005\022\022\n\nisComplete\030\003 \001(\010\022\022" +
      "\n\nisRedeemed\030\004 \001(\010B\027B\025AchievementStuffPr" +
      "oto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lvl6_proto_AchievementProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lvl6_proto_AchievementProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_AchievementProto_descriptor,
              new java.lang.String[] { "AchievementId", "Name", "Description", "GemReward", "Lvl", "AchievementType", "ResourceType", "Element", "Quality", "StaticDataId", "Quantity", "Priority", "PrerequisiteId", "SuccessorId", },
              com.lvl6.proto.AchievementStuffProto.AchievementProto.class,
              com.lvl6.proto.AchievementStuffProto.AchievementProto.Builder.class);
          internal_static_com_lvl6_proto_UserAchievementProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_lvl6_proto_UserAchievementProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_UserAchievementProto_descriptor,
              new java.lang.String[] { "AchievementId", "Progress", "IsComplete", "IsRedeemed", },
              com.lvl6.proto.AchievementStuffProto.UserAchievementProto.class,
              com.lvl6.proto.AchievementStuffProto.UserAchievementProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.proto.MonsterStuffProto.getDescriptor(),
          com.lvl6.proto.SharedEnumConfigProto.getDescriptor(),
          com.lvl6.proto.StructureProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
