package com.lvl6.mobsters.services.common;

public enum Lvl6MobstersStatusCode
{
	SUCCESS,
	SUCCESS_REQUEST,
	SUCCESS_JOIN,
	FAIL_OTHER,
	FAIL_USER_WITH_UDID_ALREADY_EXISTS,
	FAIL_USER_WITH_FACEBOOK_ID_EXISTS,
	FAIL_FB_ID_EXISTS,
	FAIL_USER_FB_ID_ALREADY_SET,
	FAIL_NOT_USERS_STRUCT, //means: fail, not user's struct
	FAIL_AT_MAX_LEVEL,
	FAIL_CONSTRUCTION_INCOMPLETE,
	
	FAIL_INSUFFICIENT_CASH,
	FAIL_INSUFFICIENT_OIL,
	FAIL_INSUFFICIENT_GEMS,
	FAIL_INSUFFICIENT_RESOURCE,
	FAIL_INSUFFICIENT_RESOURCES,
	
	FAIL_NOT_AVAIL_TO_USER, //EventQuest.proto, means the quest is not available to the user
	FAIL_ALREADY_ACCEPTED, //EventQuest.proto, means the quest is already accepted
	FAIL_NO_QUEST_EXISTS,
	FAIL_DELETE_AMOUNT_DOES_NOT_MATCH_QUEST, //EventQuest.proto, amount of monsters user is deleting inconsistent with quest requirement
	FAIL_NONEXISTENT_USER_MONSTERS,
	FAIL_INCOMPLETE_USER_MONSTERS, //EventQuest.proto, monsters user is deleting are incomplete, they need to be complete
	FAIL_QUEST_JOB_INCOMPLETE,
	FAIL_NOT_COMPLETE, //EventQuest.proto, the quest is not complete
	
	FAIL_ENEMY_UNAVAILABLE,
	FAIL_BATTLE_TOOK_TOO_LONG,
	
	FAIL_MONSTER_REACHED_EVOLVING_LIMIT,
	FAIL_EVOLUTION_CAPACITY_REACHED,
	FAIL_INSUFFICIENT_USER_MONSTERS,
	FAIL_INSUFFICIENT_FACEBOOK_INVITES,
	FAIL_INCONSISTENT_INVITE_DATA,
	FAIL_STRUCTURE_AT_MAX_FB_INVITE_LVL,
	FAIL_MORE_THAN_ONE_MONSTER_FOR_SPEEDUP,
	
	FAIL_NO_MINI_JOB_EXISTS,
	
	FAIL_DUPLICATE_RECEIPT,
	
	FAIL_NAME_TAKEN,
	FAIL_ALREADY_IN_CLAN,
	FAIL_INVALID_TAG_LENGTH,
	FAIL_TAG_TAKEN,
	FAIL_NOT_IN_CLAN,
	FAIL_OWNER_OF_CLAN_WITH_OTHERS_STILL_IN,
	FAIL_REQUEST_ALREADY_FILED,
	FAIL_CLAN_IS_FULL,
	FAIL_NONEXISTENT_JOIN_CLAN_REQUEST,
	FAIL_NOT_AUTHORIZED,
	FAIL_NONEXISTENT_CLAN_MEMBER,
	
	FAIL_MSG_TOO_LONG,
	FAIL_BANNED,
	FAIL_EMPTY_MSG,
	
	FAIL_ACHIEVEMENT_INCOMPLETE,
	FAIL_ACHIEVEMENT_ALREADY_REDEEMED,
	
	/*REMOVE/MODIFY
	 * 
	 *EventUser.proto
	 * 	UserCreateStatus
	 * 		FAIL_INVALID_NAME
	 * 		FAIL_INVALID_REFER_CODE
	 * 
	 *EventStructure.proto
	 * 	MoveOrRotateNormStructureStatus
	 * 		OTHER_FAIL ---BECOMES---> FAIL_OTHER
	 * 	
	 *	UpgradeNormStructureStatus
	 *		FAIL_NOT_ENOUGH_CASH ---BECOMES---> FAIL_INSUFFICIENT_CASH
	 *		FAIL_NOT_ENOUGH_GEMS ---BECOMES---> FAIL_INSUFFICENT_GEMS
	 *		FAIL_NOT_ENOUGH_OIL ---BECOMES---> FAIL_INSUFFICIENT_OIL
	 *		FAIL_NOT_BUILT_YET ---BECOMES---> FAIL_CONSTRUCTION_INCOMPLETE
	 *		FAIL_AT_MAX_LEVEL_ALREADY ---BECOMES---> FAIL_AT_MAX_LEVEL
	 *
	 *	FinishNormStructWaittimeStatus
	 *		FAIL_NOT_ENOUGH_GEMS ---BECOMES---> FAIL_INSUFFICENT_GEMS
	 *	
	 *	NormStructWaitCompleteStatus
	 *		FAIL_NOT_DONE_YET ---BECOMES---> FAIL_CONSTRUCTION_INCOMPLETE
	 *
	 *EventPvp.proto
	 *	QueueUpStatus
	 *		FAIL_NOT_ENOUGH_CASH ---BECOMES---> FAIL_INSUFFICIENT_CASH
	 *		FAIL_NOT_ENOUGH_GEMS ---BECOMES---> FAIL_INSUFFICENT_GEMS
	 *
	 *EventMonster.proto
	 *	EvolveMonsterStatus
	 *		FAIL_MAX_NUM_EVOLUTIONS_REACHED ---BECOMES---> FAIL_EVOLUTION_CAPACITY_REACHED
	 *		FAIL_NONEXISTENT_MONSTERS ---BECOMES---> FAIL_INSUFFICIENT_USER_MONSTERS
	 *		
	 *	EnhancementWaitTimeCompleteStatus
	 *		FAIL_HEALING_NOT_COMPLETE
	 *		FAIL_INSUFFICIENT_FUNDS ---BECOMES---> FAIL_INSUFFICIENT_GEMS
	 *	
	 *	UpdateMonsterHealthStatus
	 *		FAIL_INSUFFICIENT_FUNDS
	 *	
	 *	HealMonsterStatus
	 *		FAIL_INSUFFICIENT_FUNDS ---BECOMES---> FAIL_INSUFFICIENT_RESOURCES
	 *		FAIL_ALL_MONSTERS_ALREADY_HEALING
	 *		FAIL_ALL_MONSTERS_NONEXISTENT
	 *		FAIL_HEALING_NOT_COMPLETE
	 *
	 *	IncreaseMonsterInventorySlotStatus
	 *		FAIL_INSUFFICIENT_FUNDS ---BECOMES---> FAIL_INSUFFICIENT_RESOURCES
	 *	
	 *	AcceptAndRejectFbInviteForSlotsStatus
	 *		FAIL_EXPIRED
	 *		FAIL_ALREADY_BEEN_USED
	 *	
	 *EventMiniJob.proto
	 *	BeginMiniJobStatus
	 *		
	 *EventInAppPurchase.proto
	 *	InAppPurchaseStatus
	 *		FAIL ---BECOMES---> FAIL_OTHER		
	 *		DUPLICATE_RECEIPT ---BECOMES---> FAIL_DUPLICATE_RECEIPT
	 *
	 *EventDungeon.proto
	 *	ReviveInDungeonStatus
	 *		FAIL_INSUFFICIENT_FUNDS ---BECOMES---> FAIL_INSUFFICIENT_GEMS 
	 *
	 *EventClan.proto
	 *	CreateClanStatus
	 *		FAIL_NOT_ENOUGH_CASH ---BECOMES---> FAIL_INSUFFICIENT_CASH
	 *		FAIL_INSUFFICIENT_FUNDS ---BECOMES---> FAIL_INSUFFICIENT_GEMS
	 *
	 *	RetractRequestJoinClanStatus
	 *		FAIL_DID_NOT_REQUEST ---BECOMES---> FAIL_JOIN_CLAN_REQUEST_NONEXISTENT
	 *
	 *	ApproveOrRejectRequestToJoinClanStatus
	 *		FAIL_NOT_A_REQUESTER ---BECOMES---> FAIL_NONEXISTENT_JOIN_CLAN_REQUEST
	 *
	 *	RetrieveClanInfoStatus
	 *		OTHER_FAIL ---BECOMES---> FAIL_OTHER
	 *	
	 *	TransferClanOwnershipStatus
	 *		 FAIL_NEW_OWNER_NOT_IN_CLAN ---BECOMES---> FAIL_NONEXISTENT_CLAN_MEMBER
	 *
	 *	BootPlayerFromClanStatus
	 *		FAIL_BOOTED_NOT_IN_CLAN ---BECOMES---> FAIL_NONEXISTENT_CLAN_MEMBER
	 *
	 *EventCity.proto
	 *	LoadPlayerCityStatus
	 *		FAIL_NO_SUCH_PLAYER ---BECOMES---> FAIL_NONEXISTENT_USER
	 *
	 *	LoadCityStatus
	 *		NOT_ACCESSIBLE_TO_USER
	 *		OTHER_FAIL ---BECOMES---> FAIL_OTHER
	 *
	 *EventChat.proto
	 *	SendGroupChatStatus
	 *		TOO_LONG ---BECOMES---> FAIL_MSG_TOO_LONG
	 *		OTHER_FAIL ---BECOMES---> FAIL_OTHER
	 *		BANNED ---BECOMES---> FAIL_BANNED
	 *	
	 *	PrivateChatPostStatus
	 *		NO_CONTENT_SENT ---BECOMES---> FAIL_EMPTY_MSG
	 *		POST_TOO_LARGE ---BECOMES---> FAIL_MSG_TOO_LONG
	 *		OTHER_FAIL ---BECOMES---> FAIL_OTHER
	 *
	 *EventApns.proto
	 *		NOT_ENABLED ---BECOMES---> FAIL_OTHER
	 *
	 *EventAchievement.proto
	 *		FAIL_NOT_COMPLETED ---BECOMES---> FAIL_ACHIEVEMENT_INCOMPLETE
	 *		FAIL_ALREADY_REDEEMED ---BECOMES---> FAIL_ACHIEVEMENT_ALREADY_REDEEMED
	 */
}
